import Head from 'next/head'
// import Image from 'next/image'
import {useEffect, useState} from "react";
import { useRouter } from 'next/router'
// import { useAuth } from "@clerk/nextjs";

import { SignedIn, SignedOut, useUser, SignIn } from "@clerk/clerk-react";
import { Badge, Container } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import { UserButton, useAuth } from "@clerk/clerk-react";


export default function Home() {
  const router = useRouter();
  const {isLoaded, userId} = useAuth();

  if(userId) router.push('/todos');

  return (
    <>
      <Head>  
        <title>Kailash's To-do app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignedIn>
        
      </SignedIn>
      <SignedOut>
      
      <Container className="d-flex justify-content-center align-items-center">
      <div className=''>
          <h1 className="display-3 font-weight-bold mb-0 pt-md-5">Welcome to my to-do app!</h1>
          <hr className="hr-light" />
      </div>
      </Container>
      <Container className="d-flex justify-content-center align-items-center">
      <SignIn redirectUrl='/todos'/>
      </Container>
      </SignedOut>
      
    </>
  )
}
